### ISSUE TITLE
Inkompatibel mit Hibiscus 2.10.17

### ISSUE THREAD

**Issue by b3nn0** [faiteanu/hibiscus.docmanager#9]
Offenbar hat sich der Konstruktor für RangeInput geändert:
```
  public RangeInput(final Input from, final Input to, final Category category, final String parameter)
```

Somit kommt es bei der Verwendung des Plugins zu einem Fehler:
```
java.lang.NoSuchMethodError: 'void de.willuhn.jameica.hbci.gui.input.RangeInput.<init>(de.willuhn.jameica.gui.input.Input, de.willuhn.jameica.gui.input.Input, java.lang.String, java.lang.String)'
	at name.aiteanu.docmanager.gui.controller.DocumentListController.getRange(DocumentListController.java:254)
	at name.aiteanu.docmanager.gui.view.DocumentList.bind(DocumentList.java:49)
	at de.willuhn.jameica.gui.GUI$5.run(GUI.java:724)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at de.willuhn.jameica.gui.GUI$6.run(GUI.java:921)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5960)
	at de.willuhn.jameica.gui.GUI.startSync(GUI.java:917)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:601)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:536)
	at name.aiteanu.docmanager.gui.action.ListDocuments.handleAction(ListDocuments.java:15)
	at de.willuhn.jameica.gui.Navigation.start(Navigation.java:394)
	at de.willuhn.jameica.gui.Navigation.access$500(Navigation.java:48)
	at de.willuhn.jameica.gui.Navigation$MyActionListener.handleEvent(Navigation.java:489)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:938)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:335)
	at de.willuhn.jameica.system.Application.init(Application.java:145)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:78)
```

**Comment by faiteanu** [comment]
Danke für den Hinweis. Es ist doch toll, wenn bei einer Änderung an der 2. Nachkommastelle der Versionsnummer plötzlich Code-Änderungen enthalten sind, die Plugins kaputt machen. :-/
Mit dem Update auf DocManager 0.2.6 ist das Problem behoben.
